version: '3'

services:
    mysql:
        image: mysql:5
        volumes:
            - ./docker/mySqlDbData:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: MyDb
            MYSQL_USER: myuser
            MYSQL_PASSWORD: myuserpassword
        ports:
            - 3306:3306